"use client";

import { COLLEGE_LOCATION, COLLEGE_NAME, APP_NAME } from "./constants";
import { toCSV } from "./utils";

export type ExportRow = Record<string, string | number | null | undefined>;

function download(blob: Blob, fileName: string) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = fileName;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  // Revoking immediately can cancel the download in Safari.
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function stamp(): string {
  return new Date().toISOString().slice(0, 10);
}

export function exportCSV(rows: ExportRow[], baseName: string) {
  const csv = toCSV(rows);
  download(
    new Blob([`﻿${csv}`], { type: "text/csv;charset=utf-8;" }),
    `${baseName}-${stamp()}.csv`,
  );
}

/**
 * SheetJS and jsPDF are both large; loading them on demand keeps them out of
 * the initial bundle for every report page.
 */
export async function exportExcel(
  rows: ExportRow[],
  baseName: string,
  sheetName = "Report",
) {
  const XLSX = await import("xlsx");

  const sheet = XLSX.utils.json_to_sheet(rows);
  if (rows.length > 0) {
    sheet["!cols"] = Object.keys(rows[0]).map((key) => ({
      wch: Math.min(
        42,
        Math.max(
          key.length + 2,
          ...rows.slice(0, 300).map((row) => String(row[key] ?? "").length + 2),
        ),
      ),
    }));
    sheet["!autofilter"] = {
      ref: XLSX.utils.encode_range({
        s: { c: 0, r: 0 },
        e: { c: Object.keys(rows[0]).length - 1, r: rows.length },
      }),
    };
  }

  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, sheet, sheetName.slice(0, 31));

  const buffer = XLSX.write(workbook, { bookType: "xlsx", type: "array" });
  download(
    new Blob([buffer], {
      type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    }),
    `${baseName}-${stamp()}.xlsx`,
  );
}

export async function exportPDF(
  rows: ExportRow[],
  baseName: string,
  title: string,
  subtitle?: string,
) {
  const { jsPDF } = await import("jspdf");
  const autoTable = (await import("jspdf-autotable")).default;

  const columns = rows.length > 0 ? Object.keys(rows[0]) : [];
  // Wide reports read far better in landscape.
  const doc = new jsPDF({
    orientation: columns.length > 6 ? "landscape" : "portrait",
    unit: "pt",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(18, 41, 77);
  doc.text(COLLEGE_NAME, pageWidth / 2, 38, { align: "center" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(110, 118, 132);
  doc.text(COLLEGE_LOCATION, pageWidth / 2, 52, { align: "center" });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(200, 16, 46);
  doc.text(title, pageWidth / 2, 72, { align: "center" });

  if (subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(110, 118, 132);
    doc.text(subtitle, pageWidth / 2, 86, { align: "center" });
  }

  autoTable(doc, {
    startY: subtitle ? 98 : 86,
    head: [columns],
    body: rows.map((row) => columns.map((col) => String(row[col] ?? "—"))),
    styles: { fontSize: 7.5, cellPadding: 3.5, overflow: "linebreak" },
    headStyles: {
      fillColor: [18, 41, 77],
      textColor: 255,
      fontStyle: "bold",
      fontSize: 7.5,
    },
    alternateRowStyles: { fillColor: [246, 248, 251] },
    margin: { top: 40, left: 28, right: 28, bottom: 34 },
    didDrawPage: () => {
      const pageHeight = doc.internal.pageSize.getHeight();
      const page = doc.getNumberOfPages();
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.5);
      doc.setTextColor(150, 157, 170);
      doc.text(
        `Generated by ${APP_NAME} · ${new Date().toLocaleString("en-IN")}`,
        28,
        pageHeight - 16,
      );
      doc.text(`Page ${page}`, pageWidth - 28, pageHeight - 16, {
        align: "right",
      });
    },
  });

  doc.save(`${baseName}-${stamp()}.pdf`);
}
